### ISSUE TITLE
[RubyGem] Bump Active Support Dependency

### ISSUE THREAD

**Issue by waveofphase** [tremendous-rewards/tremendous-ruby#6]
According to this:

https://github.com/advisories/GHSA-2p68-f74v-9wc6

we should be using Rails versions
 >= 5.0.0, <= 5.2.4.2 or 
>= 6.0.0, <= 6.0.3 | 6.0.3.1

It appears Tremendous is currently only supported with `activesupport` >= 3.2, <= 5.2.3, even though the `gemspec` is pointing to `'activesupport', '>= 3.2', '<= 6.0.0.rc1'`

**Comment by kapilkale** [comment]
.gemspec now includes `spec.add_runtime_dependency 'activesupport', '>= 3.2', '< 6.2'`, so should be good
