### ISSUE TITLE
Webhook events enumerated

### ISSUE THREAD

**Issue by cromulus** [tremendous-rewards/tremendous-ruby#7]
Hi!

Is there a list of the web hook events sent, and what they mean?  On the TestFlight server, I'm only receiving ORDERS.CREATED events. It would be tremendously helpful to get events on rewards delivered, opened/viewed, redeemed, cancelled, etc. 

Thanks!

**Comment by kapilkale** [comment]
These are listed here: https://developers.tremendous.com/reference/webhooks-1
