### ISSUE TITLE
Error parsing response

### ISSUE THREAD

**Issue by cromulus** [tremendous-rewards/tremendous-ruby#8]
I'm occasionally getting this error making requests to both production and sandbox:
` unexpected token at 'Retry later (JSON::ParserError)` 

It looks as if the API response is unhandled by this gem. I have retry logic in my implementation, so it would be useful for the gem to surface when your service would like the retry to occur or at least handle the response in a way that isn't a JSON parse error.

Thanks!

**Comment by kapilkale** [comment]
Apologies for the late response here. Fix going out tonight that will force 429 (rate limit responses) to include the header `{ 'Content-Type' => 'application/json'}, which should fix this

**Comment by kapilkale** [comment]
(should be live shortly)
